encoder: eend_ola_transformer
encoder_conf:
    idim: 345
    n_layers: 4
    n_units: 256

encoder_decoder_attractor: eda
encoder_decoder_attractor_conf:
    n_units: 256

model: eend_ola
model_conf:
    max_n_speaker: 8

accum_grad: 1
max_epoch: 100
patience: none
init: none
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 100

optim: adam
optim_conf:
    lr: 0.0625
    betas: (0.9, 0.98)
    eps: 1.0e-9
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 100000

dataset_conf:
    batch_size: 64

log_interval: 50
seed: 777